### ISSUE TITLE
Says I don´t have permission

### ISSUE THREAD

**Issue by atuamaedefour** [osiris2600/fedora-setup#5]
![Captura de ecrã de 2023-12-04 22-23-14](https://github.com/smittix/fedora-setup/assets/139357594/c3a51fa0-7d8b-4dfe-8ad3-1d0fb55cea22)
When I try to execute it. It says Permission Refused.
Could you help me pls ?
Thx
Bernas

**Comment by smittix** [comment]
Hi, I guess you fixed this now but in case anyone has the same issue in future you need do chmod +x fedora-setup.sh.
